import { expect, test, type Page } from "@playwright/test";
import { join } from "node:path";
import {
  clippingOffenders,
  collectHiding,
  collectTestids,
  horizontalOverflow,
  TAP_MIN,
  tapTargetOffenders,
} from "./phone-helpers";
import {
  FIXTURE_ACCOUNT_A,
  registerCurrentAccount,
  signUpFresh,
} from "./setup-accounts";

// THE PHONE IMPORT JOURNEY (M3-P4, criterion 4.1, DR-0022).
//
// The whole PDF import runs at 390 by 844 (the chromium-phone project, and
// also the desk project, where the spec sets the phone viewport itself; the
// isMobile width guard below is only meaningful under the phone project):
// upload, the declaration a card asks at first sight, the confirmation a
// registered account gets, the result, and the month the two statements
// close. Every one of those screens is held to the three standing phone
// measurements M3-P7 introduced, with the SAME instruments the month view
// uses (test/e2e/phone-helpers.ts):
//
//   1. every interactive element inside the header and main is at least
//      44 CSS pixels tall;
//   2. the sorted (data-testid, trimmed text) pairs are deeply equal at
//      1280 by 720 and at 390 by 844, every one of them non-zero at the
//      phone width, and nothing is hidden at the phone that the desk shows;
//   3. the clipping sweep returns no offender on either axis.
//
// and, as the phase always asked, the document never scrolls sideways.
//
// Only committed synthetic fixtures are uploaded (hazard H4.3): the three
// PDFs are generated by test/fixtures/generate-pdf-fixtures.ts, the CSV is
// a committed synthetic fixture, and both account numbers registered below
// are invented and listed with their provenance in
// test/fixtures/allowed-identifiers.txt.

// The second journey (fix round 1, findings CR-M3P4-01 and HZ-M3P4-01)
// reaches the branches the PDF journey never shows: the format question a
// CSV from an unseen format asks, with its description disclosure opened,
// the note on a file whose account the household never registered, and the
// refusal line the confirm step then returns. Each carries a control the
// first journey could not measure.

const PHONE = { width: 390, height: 844 } as const;
const DESK = { width: 1280, height: 720 } as const;

const BELFIUS_PDF_ACCOUNT = "BE72012345678944";
const KBC_FIXTURE = join(__dirname, "..", "fixtures", "kbc-statement-a.pdf");
const CSV_FIXTURE = join(__dirname, "..", "fixtures", "belfius-account-a.csv");
const UNREGISTERED_PDF_FIXTURE = join(
  __dirname,
  "..",
  "fixtures",
  "belfius-statement-a.pdf",
);
const COMPANION_FIXTURE = join(
  __dirname,
  "..",
  "fixtures",
  "belfius-settlement-companion.pdf",
);

// One screen, measured at the phone width and compared against the desk
// width. Soft assertions so a failing screen names every offender at once;
// the journey carries on to the next screen either way, and the test still
// fails at the end.
const measureScreen = async (page: Page, screen: string): Promise<void> => {
  await page.setViewportSize(PHONE);

  const overflow = await horizontalOverflow(page);
  expect
    .soft(overflow.scrollWidth, `${screen}: document scrolls sideways`)
    .toBeLessThanOrEqual(overflow.clientWidth);

  expect
    .soft(await tapTargetOffenders(page), `${screen}: tap targets under 44px`)
    .toEqual([]);

  const clipping = await clippingOffenders(page);
  expect
    .soft(clipping.horizontal, `${screen}: horizontal clipping`)
    .toEqual([]);
  expect.soft(clipping.vertical, `${screen}: vertical clipping`).toEqual([]);

  const phone = await collectTestids(page);
  const phoneHiding = await collectHiding(page);
  await page.setViewportSize(DESK);
  const desk = await collectTestids(page);
  const deskHiding = await collectHiding(page);
  await page.setViewportSize(PHONE);

  expect
    .soft(
      phone.map((entry) => [entry.testId, entry.text]),
      `${screen}: testid and text differ between desk and phone`,
    )
    .toEqual(desk.map((entry) => [entry.testId, entry.text]));
  expect
    .soft(
      phone
        .filter((entry) => entry.width <= 0 || entry.height <= 0)
        .map((entry) => entry.testId),
      `${screen}: testid elements with no size at the phone width`,
    )
    .toEqual([]);
  expect
    .soft(phoneHiding, `${screen}: hiding state differs between widths`)
    .toEqual(deskHiding);
};

test("the PDF import journey is usable at 390 by 844, screen by screen", async ({
  page,
}) => {
  // Two uploads, five measured screens and a month view after a sign-up.
  test.setTimeout(180_000);
  await page.setViewportSize(PHONE);

  await signUpFresh(page, "mobile-import");
  await registerCurrentAccount(
    page,
    BELFIUS_PDF_ACCOUNT,
    "Daily account",
    "Belfius",
  );

  // Upload.
  await page.goto("/import");
  await expect(page.getByRole("heading", { name: "Import" })).toBeVisible();
  // Guard, as month-view.spec.ts does, read on a real page because a blank
  // one has no meta viewport: the browser honours the tag under this
  // project's isMobile emulation, so the width the layout sees is the
  // device width and not a desktop layout viewport.
  expect(await page.evaluate(() => window.innerWidth)).toBe(PHONE.width);
  await measureScreen(page, "import");

  // A card statement: recognised layout, no format question, and the
  // account declaration asked at first sight.
  await page.getByLabel("Bank export file").setInputFiles(KBC_FIXTURE);
  await page.getByRole("button", { name: "Upload" }).click();
  await expect(
    page.getByRole("heading", { name: "Confirm the detected format" }),
    // First compile of the confirmation route plus a PDF parse on the dev
    // server outlasts the default five seconds on a cold run.
  ).toBeVisible({ timeout: 30_000 });
  await expect(page.getByTestId("account-declaration")).toBeVisible();
  await expect(page.getByTestId("preview-row")).toHaveCount(5);
  await measureScreen(page, "declaration");

  await page.getByLabel("Label").fill("Credit card");
  await page.getByLabel("Bank").fill("KBC");
  await page.getByTestId("confirm-import").click();
  await expect(page.getByTestId("import-result")).toBeVisible({
    timeout: 30_000,
  });
  await expect(page.getByTestId("rows-added")).toHaveText("9");
  await measureScreen(page, "result (card)");

  // The companion statement lands in the account registered at setup, so
  // its confirmation asks nothing.
  await page.goto("/import");
  await page.getByLabel("Bank export file").setInputFiles(COMPANION_FIXTURE);
  await page.getByRole("button", { name: "Upload" }).click();
  await expect(
    page.getByRole("heading", { name: "Confirm the detected format" }),
    // First compile of the confirmation route plus a PDF parse on the dev
    // server outlasts the default five seconds on a cold run.
  ).toBeVisible({ timeout: 30_000 });
  await expect(page.getByTestId("account-declaration")).toHaveCount(0);
  await expect(page.getByTestId("landing-account")).toContainText(
    "Daily account",
  );
  await measureScreen(page, "confirmation");

  await page.getByTestId("confirm-import").click();
  await expect(page.getByTestId("import-result")).toBeVisible({
    timeout: 30_000,
  });
  await expect(page.getByTestId("rows-added")).toHaveText("4");
  await measureScreen(page, "result (account)");

  // The month both statements close.
  await page.goto("/?month=2026-06");
  await expect(page.getByTestId("recon-panel")).toHaveAttribute(
    "data-state",
    "ok",
  );
  await measureScreen(page, "month");
});

test("the format question, the unregistered account and the refusal are usable at 390 by 844", async ({
  page,
}) => {
  test.setTimeout(180_000);
  await page.setViewportSize(PHONE);

  await signUpFresh(page, "mobile-import-branches");
  // Only the CSV's own account is registered, so the PDF uploaded after it
  // names an account this household never entered.
  await registerCurrentAccount(page, FIXTURE_ACCOUNT_A);

  // An unseen CSV format: the format question with its description
  // disclosure, measured closed and then open, where the preview action
  // becomes reachable.
  await page.goto("/import");
  await page.getByLabel("Bank export file").setInputFiles(CSV_FIXTURE);
  await page.getByRole("button", { name: "Upload" }).click();
  await expect(
    page.getByRole("heading", { name: "Confirm the detected format" }),
  ).toBeVisible({ timeout: 30_000 });
  await expect(page.getByLabel("Format name")).toBeVisible();
  await measureScreen(page, "format question");

  // The disclosure toggle is a control, but the shared INTERACTIVE selector
  // does not match summary, so the sweep above cannot see it; it is
  // measured here directly, at the same minimum.
  const summaryBox = await page.locator(".spec-editor summary").boundingBox();
  expect(summaryBox?.height ?? 0, "description toggle height").toBeGreaterThanOrEqual(
    TAP_MIN,
  );

  await page.locator(".spec-editor summary").click();
  await expect(page.getByRole("button", { name: "Preview again" })).toBeVisible();
  await measureScreen(page, "format question, description open");

  // A PDF for an account nobody registered: the note says so before the
  // submit and links to setup.
  await page.goto("/import");
  await page.getByLabel("Bank export file").setInputFiles(UNREGISTERED_PDF_FIXTURE);
  await page.getByRole("button", { name: "Upload" }).click();
  await expect(page.getByTestId("landing-unregistered")).toBeVisible({
    timeout: 30_000,
  });
  await measureScreen(page, "unregistered account");

  // The confirm step refuses it, and the refusal line links to setup.
  await page.getByTestId("confirm-import").click();
  await expect(page.getByTestId("import-status")).toBeVisible({
    timeout: 30_000,
  });
  await expect(
    page.getByTestId("import-status").getByRole("link"),
  ).toBeVisible();
  await measureScreen(page, "refusal");
});
