import { PrismaClient } from "@prisma/client";
import { expect, test } from "@playwright/test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { measurePhoneScreen } from "./phone-helpers";
import { registerCurrentAccount, signUpFresh } from "./setup-accounts";

// THE SHARE-SHEET ENTRY POINT (M3-P5, DR-0021, criteria 5.1, 5.4 and 5.5).
//
// A phone's share sheet POSTs the shared file to the manifest's
// share_target as multipart form data, with no JavaScript of the app's own
// involved. These tests make exactly that request with Playwright's API
// client and then open the page the redirect names, which is what the
// installed app does after a share.
//
// Only committed synthetic fixtures are posted (both PDFs are generated by
// test/fixtures/generate-pdf-fixtures.ts), and the one account number
// registered below is invented and listed with its provenance in
// test/fixtures/allowed-identifiers.txt.

const SHARE_PATH = "/import/share";
const BELFIUS_PDF_ACCOUNT = "BE72012345678944";
const fixture = (name: string) => join(__dirname, "..", "fixtures", name);
const STATEMENT = "belfius-statement-a.pdf";
const COMPANION = "belfius-settlement-companion.pdf";

const sharedFile = (name: string) => ({
  file: {
    name,
    mimeType: "application/pdf",
    buffer: readFileSync(fixture(name)),
  },
});

// The Import table is where uploaded bytes are kept (Import.rawContent), so
// "nothing was kept" is measured as "no Import row appeared". The suite runs
// one worker, so the global count moves only when this test moves it.
let client: PrismaClient | undefined;
const importCount = (): Promise<number> => {
  if (client === undefined) {
    throw new Error("the Prisma client is constructed in beforeAll");
  }
  return client.import.count();
};

test.beforeAll(() => {
  client = new PrismaClient();
});

test.afterAll(async () => {
  await client?.$disconnect();
});

test("the manifest is served without a session and declares a PDF share target", async ({
  request,
}) => {
  const response = await request.get("/manifest.webmanifest", { maxRedirects: 0 });
  expect(response.status()).toBe(200);
  const body = (await response.json()) as {
    share_target: {
      action: string;
      method: string;
      enctype: string;
      params: { files: { name: string; accept: string[] }[] };
    };
    icons: { src: string }[];
  };
  expect(body.share_target.action).toBe(SHARE_PATH);
  expect(body.share_target.method).toBe("POST");
  expect(body.share_target.enctype).toBe("multipart/form-data");
  expect(body.share_target.params.files).toEqual([
    { name: "file", accept: ["application/pdf", ".pdf"] },
  ]);
  // Every icon the manifest names resolves, without a session, to a PNG.
  for (const icon of body.icons) {
    const image = await request.get(icon.src, { maxRedirects: 0 });
    expect(image.status(), icon.src).toBe(200);
    expect(image.headers()["content-type"], icon.src).toContain("image/png");
  }
});

test("an unauthenticated share goes to sign-in with a 303 and nothing is kept", async ({
  request,
}) => {
  const before = await importCount();
  const response = await request.post(SHARE_PATH, {
    multipart: sharedFile(STATEMENT),
    maxRedirects: 0,
  });
  // 303, not 307: a 307 would make the browser repeat the POST, file and
  // all, at the sign-in page (decision D-10).
  expect(response.status()).toBe(303);
  expect(new URL(response.headers()["location"] ?? "", "http://x").pathname).toBe(
    "/sign-in",
  );
  expect(await importCount()).toBe(before);
});

test("a share POSTed from another site's page is refused and nothing is kept", async ({
  page,
}) => {
  await signUpFresh(page, "share-cross-site");
  await registerCurrentAccount(page, BELFIUS_PDF_ACCOUNT, "Daily account", "Belfius");
  const before = await importCount();
  const response = await page.request.post(SHARE_PATH, {
    multipart: sharedFile(STATEMENT),
    headers: { origin: "https://elsewhere.example" },
    maxRedirects: 0,
  });
  expect(response.status()).toBe(403);
  expect(await importCount()).toBe(before);
});

test("a shared PDF lands in the import flow, usable at 390 by 844", async ({ page }) => {
  test.setTimeout(180_000);
  await page.setViewportSize({ width: 390, height: 844 });
  await signUpFresh(page, "share-target");
  await registerCurrentAccount(page, BELFIUS_PDF_ACCOUNT, "Daily account", "Belfius");

  // First share: a layout this household has not confirmed yet, so the
  // share lands on the confirmation screen, exactly where an upload of the
  // same file lands.
  const first = await page.request.post(SHARE_PATH, {
    multipart: sharedFile(STATEMENT),
    maxRedirects: 0,
  });
  expect(first.status()).toBe(303);
  const firstLanding = first.headers()["location"] ?? "";
  expect(new URL(firstLanding, "http://x").pathname).toMatch(/^\/import\/[0-9a-f-]{36}$/);
  await page.goto(firstLanding);
  await expect(
    page.getByRole("heading", { name: "Confirm the detected format" }),
  ).toBeVisible({ timeout: 30_000 });
  await expect(page.getByTestId("landing-account")).toContainText("Daily account");
  await measurePhoneScreen(page, "share landing: confirmation");

  await page.getByTestId("confirm-import").click();
  await expect(page.getByTestId("import-result")).toBeVisible({ timeout: 30_000 });
  await expect(page.getByTestId("rows-added")).toHaveText("9");

  // Second share, followed through its redirect chain the way the browser
  // follows it: the layout is known now, so the chain ends on the result
  // with the fixture's rows added and nothing asked.
  const second = await page.request.post(SHARE_PATH, {
    multipart: sharedFile(COMPANION),
  });
  expect(second.status()).toBe(200);
  const secondLanding = new URL(second.url()).pathname;
  expect(secondLanding).toMatch(/^\/import\/[0-9a-f-]{36}$/);
  await page.goto(secondLanding);
  await expect(page.getByTestId("import-result")).toBeVisible({ timeout: 30_000 });
  await expect(page.getByTestId("landing-account")).toHaveText("Daily account");
  await expect(page.getByTestId("rows-added")).toHaveText("4");
  await measurePhoneScreen(page, "share landing: result");
});
